[package]
name = "esquema-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
atrium-api.workspace = true
atrium-xrpc-client.workspace = true
clap = { version = "4.4.18", features = ["derive"] }
dotenv = "0.15.0"
esquema-codegen.workspace = true
tokio = { version = "1.44.1", features = ["full"] }
