// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `dev.baileytownsend` namespace.
pub mod graph;
pub mod steps;
pub mod weekly_steps;
#[derive(Debug)]
pub struct Steps;
impl atrium_api::types::Collection for Steps {
    const NSID: &'static str = "dev.baileytownsend.steps";
    type Record = steps::Record;
}
