use crate::lexicons::record::KnownRecord;
use atrium_api::types::Unknown;

// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
// !Definitions for the `xyz.statusphere.status` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    pub created_at: atrium_api::types::string::Datetime,
    pub status: String,
}
pub type Record = atrium_api::types::Object<RecordData>;

impl From<atrium_api::types::Unknown> for RecordData {
    fn from(value: Unknown) -> Self {
        value.try_into().unwrap()
    }
}
